- cubyz-client/assets/cubyz/lang/es_ES.lang
> Add spanish translation

- assets/cubyz/lang/pt_BR.lang
- assets/cubyz/lang/pt_PT.lang
Added portugal and brasil portuguese translations.
> Portuguese support.

- assets/cubyz/lang/pt_BR.lang
- assets/cubyz/lang/pt_PT.lang
This pr adds the Portuguese translations to blocks, items, and tools that were missing on the last pr.
> Missing translations on PR #16

- assets/cubyz/lang/pt_BR.lang
- assets/cubyz/lang/pt_PT.lang
- Update Portuguese (pt_pt and pt_br) to include the latest keys.
> Update portuguese to the latest translation

- src/cubyz/command/GiveCommand.java
- src/cubyz/command/TPCommand.java
- src/cubyz/command/TimeCommand.java
Another little PR with small changes to improve the gaming experience.
- **Give Command:** Allow the game id ommition.
- Before: `give cubyz:stone 10`
- After:  `give stone 10`
- **Time Command:** Made it easier (for new players) to use by adding keywords.
- Before: `time 0` or `time 52000`
- After:   `time day` or `time night` or `time <int>`
- Fix copypasta mistake in `TPCommand`
> Quality of Life: Commands

- src/cubyz/gui/input/Input.java
- Increased altitude speed when pressing left control. 
- Add same behavior as going faster on left control.
https://github.com/PixelGuys/Cubyz/blob/fa914a9fc405446dca90c2551eb2296e412ef591/src/cubyz/gui/input/Input.java#L71-L79
> Input: Increase fly speed when pressing LEFT_CONTROL

- assets/cubyz/lang/pt_BR.lang
- assets/cubyz/lang/pt_PT.lang
- Fix `langname` in pt_BR. 
- Include both pt_PT and pt_PT to the latest keys.
> PT: Montly lang update

- src/cubyz/gui/components/Button.java
- Clip the text that is bigger than the button width and make it scroll on the X-axis to make it readable.
> Button Text: Final Version.

- src/game.zig
- src/items.zig
- src/main.zig
- src/renderer.zig
I had to make a few things public though I hope that isn't an issue
> Made middle mouse click give player selected block

- README.md
Rewrites the texturing portion of the readme with more useful and accurate information. Yes, it's way longer... but hopefully it gives people a better idea of the style. Let me know what could be changed.
> Update readme texture guidelines

- build.zig
This PR attempts to resolve #460.
> Link Cubyz more correctly.

- src/game.zig
> Set velocity to 0 when colliding into a wall (fixes #493)

- src/game.zig
- src/main.zig
- src/renderer.zig
- src/renderer/mesh_storage.zig
fixes #578
fixes #560
fixes #552
fixes #551
reopens #503 
Remaining work:
Remove more old code
> Switch to an internal spring system for stepping and collision, instead of using external springs.

- format_check.py
- src/game.zig
- src/gui/windows/debug.zig
Adds more information to the f3 debug screen.
Fixed various issues that occured when running format_check.py on windows.
Refactored player collision detection to reduce repeated code.
Added "Coyote" time to eye position when walking off edge to fix #636.
Made the player always unstuck upwards to make #521 less confusing.
> Player physics fixes and more debug info

- src/server/terrain/climategen/NoiseBasedVoronoi.zig
Removed warning as discussed in https://github.com/PixelGuys/Cubyz/pull/678#issuecomment-2332412137
> Remove spammy warning from biome generation.

- assets/cubyz/blocks/vetch.json
> Made vetch visible again

- src/game.zig
> Was accidentally checking against steppingHeight instead of height.

- debug_linux.sh
- debug_windows.bat
The URL for downloading Zig seems to have changed. This PR fixes the URL in the debug scripts
> Fix Zig download url

- src/server/command/invite.zig
> fix: /invite error rename

- assets/cubyz/blocks/basalt.zig.zon
- assets/cubyz/blocks/cobblestone.zig.zon
- assets/cubyz/blocks/ferrock.zig.zon
- assets/cubyz/blocks/glacite.zig.zon
- assets/cubyz/blocks/limestone.zig.zon
- assets/cubyz/blocks/marble.zig.zon
- assets/cubyz/blocks/obsidian.zig.zon
- assets/cubyz/blocks/sandstone.zig.zon
- assets/cubyz/blocks/stone.zig.zon
- assets/cubyz/blocks/void_stone.zig.zon
> Made different stone types usable in crafting

- src/files.zig
- src/gui/windows/error_prompt.zig
- src/gui/windows/save_selection.zig
> make a open log button

- .github/workflows/ci.yml
- src/assets.zig
> Add a CI step to check if the game compiles on Linux and Windows

- src/network.zig
- src/server/server.zig
> send user id to the client

- src/game.zig
> Increased Fall Damage Start

- assets/cubyz/biomes/tundra/base.zig.zon
When you see how small this PR is, you might cry tears of joy. All I did was move it into its own folder and change the grass to dry grass.
> Tundra Revamp

- assets/cubyz/blocks/glow_crystal/_defaults.zig.zon
- assets/cubyz/recipes/special_recipes.zig.zon
> Added Lamp + Iron Block Recipe & Made Glow Crystal Collectable

- src/renderer/chunk_meshing.zig
I also set the contrast to zero, since that seemed to be preferred in general.
@ikabod-kee since I changed the implementation a bit, it would be great if you could confirm that it still works the way you want.
@careeoki please try it and confirm that this is in line with our art direction.
fixes #844 (not quite the same algorithm, but close enough).
> dynamic lighting (it's all fake)

- assets/cubyz/tools/pickaxe.zig.zon
fixes #1087
I left "gemslot" unchanged as it's reserved for modifiers.
> Added durability for binding

- src/game.zig
- src/gui/windows/debug.zig
This should make it feel better when jumping, because before it felt like i couldn't jump on the block. Maybe the time could be smaller.
> Add coyote time

- assets/cubyz/blocks/basalt.zig.zon
- assets/cubyz/blocks/coal_ore.zig.zon
- assets/cubyz/blocks/cobblestone.zig.zon
- assets/cubyz/blocks/diamond_ore.zig.zon
- assets/cubyz/blocks/ferrock.zig.zon
- assets/cubyz/blocks/glacite.zig.zon
- assets/cubyz/blocks/gold_ore.zig.zon
- assets/cubyz/blocks/limestone.zig.zon
- assets/cubyz/blocks/marble.zig.zon
- assets/cubyz/blocks/mossy_cobblestone.zig.zon
- assets/cubyz/blocks/obsidian.zig.zon
- assets/cubyz/blocks/sandstone.zig.zon
- assets/cubyz/blocks/stone.zig.zon
- assets/cubyz/blocks/void_stone.zig.zon
- assets/cubyz/items/diamond.zig.zon
- assets/cubyz/tools/pickaxe.zig.zon
I've removed cobblestone as a material, as it's a decoration block.
> Pickaxe Rebalance (2)

- src/server/terrain/biomes.zig
As discussed [here](https://github.com/PixelGuys/Cubyz/pull/1179#discussion_r1986355618), this PR uses some Stack Overflow sourced knowledge to (probably) improve `hashGeneric`.
I haven't measured that yet, I'd be glad to receive some advice in that matter (which parts of Cubyz to look at).
> (Probably) better `hashGeneric`

- src/network.zig
- src/server/server.zig
> Refactor `server.zig` to use `BinaryWriter` and `BinaryReader`

- src/blueprint.zig
- src/rotation.zig
- src/server/command/_list.zig
- src/server/command/worldedit/rotate.zig
> Add `/rotate` command

- src/assets.zig
> Fix biome migrations loading

- .github/workflows/ci.yml
- src/json.zig
- src/zon.zig
It isn't much, but why not run it in the CI? And maybe it might make sense to expand this in the future,
> Add testing to the CI

- src/server/terrain/SurfaceMap.zig
This pull request refactors SurfaceMap code to use BinaryReader and BinaryWriter for serialization. I decided to leave version 0 reading the way it is, as it is only for compatibility and I have no way of checking if I didn't mess it up.
Related to #1156
> Refactor `SurfaceMap.zig` to use `BinaryReader` and `BinaryWriter`

- src/network.zig
> Refactor `network.zig` `sendKeepAlive` and `receiveKeepAlive` to use `BinaryWriter` and `BinaryReader`

- src/Inventory.zig
- src/blueprint.zig
- src/itemdrop.zig
- src/network.zig
- src/server/server.zig
- src/server/storage.zig
- src/server/terrain/SurfaceMap.zig
- src/utils.zig
> Always use big endian

- assets/cubyz/blocks/coal_ore.zig.zon
- assets/cubyz/blocks/copper_ore.zig.zon
- assets/cubyz/blocks/diamond_ore.zig.zon
- assets/cubyz/blocks/gold_ore.zig.zon
- assets/cubyz/blocks/iron_ore.zig.zon
- assets/cubyz/blocks/sulfur_ore.zig.zon
- assets/cubyz/blocks/uranium_ore.zig.zon
fixes #1278 
I played in survival for some time and this felt pretty good. 
500: Coal
20: Copper
-250: Iron
-500: Gold (Copper stops)
-800: Sulfur
-1000: Diamond
-1500: Uranium
> Redistribute ores

- src/itemdrop.zig
- src/network.zig
- src/server/server.zig
> Use `readVec` and `writeVec` where applicable

- src/rotation/texture_pile.zig
> Fix `texture_pile`

- src/gui/components/ItemSlot.zig
Gradient from green to yellow to red
fixes #892
> Show tool durability in icon

- assets/cubyz/shaders/graphics/Image.fs
- src/gui/windows/crosshair.zig
> Make the crosshair transparent

- src/renderer/chunk_meshing.zig
- src/renderer/mesh_storage.zig
> Remove `1` from `scheduleLightRefreshAndDecreaseRefCount1`

- assets/cubyz/shaders/block_selection_fragment.frag
- assets/cubyz/shaders/block_selection_vertex.vert
- src/renderer.zig
fixes #1393
Thickness is now constant in world-space, so if you go far away it gets thinner
@ikabod-kee @careeoki please check if it's ok like this, or if you want me to make any improvements.
> Draw a thicker selection box

- src/Inventory.zig
- src/assets.zig
- src/blocks.zig
- src/game.zig
- src/gui/windows/creative_inventory.zig
- src/gui/windows/inventory_crafting.zig
- src/itemdrop.zig
- src/items.zig
- src/renderer.zig
- src/rotation.zig
- src/rotation/stairs.zig
- src/rotation/texture_pile.zig
- src/rotation/torch.zig
This pull request adds `BaseItemIndex` struct that behaves similarily to `ModelIndex` structs.
Related to: #1290 
Related to: #1060
> Add `BaseItemIndex` struct

- assets/cubyz/blocks/chest/_defaults.zig.zon
- assets/cubyz/blocks/frost.zig.zon
- assets/cubyz/blocks/ice.zig.zon
- assets/cubyz/blocks/snow.zig.zon
- src/block_entity.zig
- src/blocks.zig
- src/chunk.zig
- src/main.zig
- src/renderer/chunk_meshing.zig
- src/renderer/mesh_storage.zig
- src/server/world.zig
I also removed the legacy (java) blockEntity references.
fixes #1454
@Argmaster since you wrote the original code in #1224, please review and check if the new names are fine for you.
> Rename EntityDataClass to BlockEntityType

- src/blueprint.zig
- src/utils.zig
> Migrate all the test to use `main.heap.testingAllocator`

- src/assets.zig
- src/game.zig
- src/items.zig
- src/network.zig
- src/server/world.zig
This pull request adds a tool palette to allow using stable indexes for binary storage.
Related to: #1290 
Related to: #1478
Related to: #1473
> Add tool palette

- src/gui/windows/sign_editor.zig
just something i noticed while playing
> close the sign window when mouse is grabbed

- src/assets.zig
- src/migrations.zig
- src/utils.zig
> Add `baseItem` migrations

- src/graphics.zig
> Allow send `Add ##` in chat

- mods/cubyz/rotation/branch.zig
- mods/cubyz/rotation/carpet.zig
- mods/cubyz/rotation/direction.zig
- mods/cubyz/rotation/fence.zig
- mods/cubyz/rotation/log.zig
- mods/cubyz/rotation/planar.zig
- mods/cubyz/rotation/sign.zig
- mods/cubyz/rotation/stairs.zig
- mods/cubyz/rotation/texture_pile.zig
- mods/cubyz/rotation/torch.zig
- src/assets.zig
- src/block_entity.zig
- src/game.zig
- src/itemdrop.zig
- src/items.zig
- src/models.zig
> Use `enum` instead of `packed struct` for `*Index` objects

- mods/cubyz/rotation/log.zig
> Enable placing logs on transparent blocks

- src/graphics/Window.zig
- src/gui/windows/controls.zig
- src/settings.zig
> Added invert mouse Y setting

- assets/cubyz/blocks/duckweed.zig.zon
- assets/cubyz/blocks/lily_pad.zig.zon
- src/blocks.zig
- src/renderer.zig
- src/tag.zig
> Place certain blocks on water

- assets/cubyz/blocks/bolete.zig.zon
- assets/cubyz/blocks/bolete_branch.zig.zon
- assets/cubyz/blocks/bolete_cap.zig.zon
- assets/cubyz/blocks/bolete_stem.zig.zon
- assets/cubyz/blocks/glimmergill.zig.zon
- assets/cubyz/blocks/glimmergill_branch.zig.zon
- assets/cubyz/blocks/glimmergill_cap.zig.zon
- assets/cubyz/blocks/glimmergill_stem.zig.zon
- assets/cubyz/blocks/log/bolete.zig.zon
- assets/cubyz/blocks/log/glimmergill.zig.zon
- assets/cubyz/blocks/log/toadstool.zig.zon
- assets/cubyz/blocks/toadstool.zig.zon
- assets/cubyz/blocks/toadstool_branch.zig.zon
- assets/cubyz/blocks/toadstool_cap.zig.zon
- assets/cubyz/blocks/toadstool_stem.zig.zon
Added ".mushroom" tags suggested here #1713 
Also made the mushroom logs ".cuttable" to match the rest of the mushroom blocks.
fixes #1713
> add .mushroom tag and make mushroom logs cuttable

- GAME_DESIGN_PRINCIPLES.md
I went ahead and rephrased much of the Game Design Principles to make them clearer.
> Game Design Principles Update

- assets/cubyz/blocks/bolete_cap.zig.zon
- assets/cubyz/blocks/glimmergill_cap.zig.zon
- assets/cubyz/blocks/toadstool_cap.zig.zon
- src/blocks.zig
- src/game.zig
> Bouncy mushrooms

- src/graphics/vulkan.zig
Also generalized how the device features are handled and loader stuff.
progress towards #102
> Create the logical device and queues.

- src/Inventory.zig
- src/block_entity.zig
- src/game.zig
- src/gui/gui.zig
- src/gui/windows/creative_inventory.zig
- src/gui/windows/inventory_crafting.zig
- src/gui/windows/shared_inventory_testing.zig
- src/gui/windows/workbench.zig
- src/server/world.zig
Also adds onFirstOpen and onLastClose
> Move inventory callbacks into their own struct

- .gitignore
- src/main.zig
- src/server/command/worldedit/blueprint.zig
> Move blueprints to cubyzDir

- src/gui/windows/save_creation.zig
> Fix save crash

- src/physics.zig
> swim bug fix

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Compile for 64 bit arm in the CI

- assets/cubyz/biomes/rare/knitted/funny_pit.zig.zon
- assets/cubyz/biomes/rare/knitted/mountain.zig.zon
correction of parentBiome ids in #1860 by @careeoki
> fixed incorrect parentBiome ids
