- assets/cubyz/shaders/easyLighting/chunk_vertex.vs
- src/cubyz/client/ChunkMesh.java
- src/cubyz/client/ClientOnly.java
- src/cubyz/client/Meshes.java
- src/cubyz/client/NormalChunkMesh.java
- src/cubyz/client/ReducedChunkMesh.java
- src/cubyz/rendering/BlockPreview.java
- src/cubyz/rendering/MainRenderer.java
- src/cubyz/rendering/RenderOctTree.java
- src/cubyz/rendering/ShaderProgram.java
- src/cubyz/utils/datastructures/BinaryMaxHeap.java
- src/cubyz/world/Chunk.java
- src/cubyz/world/LocalSurface.java
- src/cubyz/world/MetaChunk.java
- src/cubyz/world/NormalChunk.java
- src/cubyz/world/ReducedChunk.java
- src/cubyz/world/terrain/ClimateMap.java
- src/cubyz/world/terrain/ClimateMapFragment.java
When the player moves around too fast the LOD-borders start flickering.
The idea is to use replacement meshes(from the higher LOD-level) that will be shown when a given mesh hasn't been created yet.
This requires some rewriting, which gives me the opportunity to also fix some other problems.
> Fix the chunk flickering bug.

- src/cubyz/gui/ConsoleLog.java
- src/cubyz/gui/UISystem.java
- src/cubyz/gui/components/Container.java
- src/cubyz/gui/components/ScrollingContainer.java
- src/cubyz/utils/Logger.java
Checking the console output while developing the game is very handy right? With this in mind, I implemented the ability to check the current log output by pressing the `L` key. 
- The `ConsoleLog` can be open from every GUI since it's added as an overlay.
- Currently, you use `L` to show and hide the `ConsoleLog` GUI.
- The ScrollContainer is automatically set to the end. 
- Log levels are available on ### DEBUG, WARN, and ERROR with the respective colors being **white, yellow, and red**.
- Add a command output to run the in-game commands, or show dev-only features.
> Log Viewer or ConsoleLogGUI

- src/cubyz/gui/components/TextInput.java
- src/cubyz/gui/game/ConsoleGUI.java
Quality of Life improvements:
- Close when Enter is pressed.
- Simulate left-click on TextInput when focusing the TextInput. (this makes the cursor to appear when you open the ConsoleGUI)
> ConsoleGUI improvements.

- src/cubyz/gui/components/Button.java
This Un-highlights clicked buttons when moved away.
Before, if you clicked on a button (without releasing the left mouse button), and moved the cursor away from the button, it would stay highlighted. Going over multiple buttons would highlight all of them as pressed.
> Prevent multi-button highlight

- src/cubyz/gui/game/inventory/CreativeGUI.java
- src/cubyz/gui/game/inventory/GeneralInventory.java
- src/cubyz/gui/game/inventory/InventoryGUI.java
- src/cubyz/gui/game/inventory/WorkbenchGUI.java
- Move all the inventory screens to the middle of the screen.
> GUI: Center GUI's on screen.

- src/cubyz/api/CurrentWorldRegistries.java
- src/cubyz/utils/translate/Language.java
- src/cubyz/utils/translate/LanguageLoader.java
- src/cubyz/world/blocks/CustomOre.java
- Implementation of the Discord idea on the translation of custom ores.
- When the world is created a language file is created with all the world custom ore translations. This file is then used as a fallback when the translation key isn't found in the main language in use. 
```properties
#Contains all the translated names for the generated ores.
block.cubyz.Wyartite_ore.name=Wyartite Ore
block.cubyz.Ekanksite_ore.name=Ekanksite Ore
block.cubyz.Vivinella_ore.name=Vivinella Ore
block.cubyz.Derssulan_ore.name=Derssulan Ore
block.cubyz.Yeliotil_ore.name=Yeliotil Ore
block.cubyz.Evesuvite_ore.name=Evesuvite Ore
block.cubyz.Kamackiter_ore.name=Kamackiter Ore
block.cubyz.Geridymium_ore.name=Geridymium Ore
```
> Fix: Custom ore .lang file.

- src/main.zig
The issue seemed to be that that the thread pool was accessing freed memory because memory was freed before all the threads were done doing stuff, my fix is to make sure that the thread pool is all cleared up before freeing anything.
I think that another way to fix this is to not deinit anything and let OS clear everything up which could improve close times.
Should fix #127
> Exit crash

- src/gui/windows/change_name.zig
In the name changing menu, "loose" is used instead of "lose". Fixed that :+1:
> Fixed spelling mistake :)

- build.zig
- build.zig.zon
Tangentially related to [this PR](https://github.com/PixelGuys/Cubyz-libs/pull/2).
> Upgrade deps

- src/blocks.zig
- src/game.zig
- src/gui/windows/main.zig
- src/gui/windows/pause.zig
- src/main.zig
- src/renderer/mesh_storage.zig
better shortcuts and most importantly: makes exiting the world possible. With this revolutionary and long awaited feature you can finally stop playing 🥳. Now people can go outside and touch some grass!
> Qol shortcuts

- src/renderer.zig
This way, the game feels more responsive at high frame times as it doesn't throttle its _meshing_ when its _rendering_ is slow.
> Measure meshing separately from rendering.

- build.zig
It should be stable enough. This way at least Mac users who don't aren't using Cubyz-libs don't have to do anything extra.
> Mac: use released deps

- assets/cubyz/biomes/cave/cave.json
- assets/cubyz/biomes/cave/marble_cave.json
- assets/cubyz/biomes/cave/stalagmite_cave.json
Resolves #562
Also some small unrelated changes:
- Normal caves are slightly foggier
- Normal caves have small stalagmites (rarely)
- Stalagmite caves have limestone ground_patches to emulate flowstone, and to distribute the limestone more evenly throughout the biome (instead of it being only on stalagmites)
- Stalagmite caves max_height raised to -256
- Stalagmite caves have fog
> Change stalagmites to simple structures

- src/gui/windows/pause.zig
- src/gui/windows/save_selection.zig
When a player boots up Cubyz for the first time, it will look like this:
Which isn't the best first impression. 
Now, with default_background, the player will have a background when playing for the first time.
We can change the image itself whenever.
Also removes the "Play" before the world name
Also removes the "TODO" from the exit button (because... it has been done!)
> Fix some text, add default_background

- src/game.zig
When you middle click a block and your selected slot has an item. Instead of overwriting it the block will get added to the first empty slot in the hotbar and it will move the selected slot to the slot, and if you have no open slots in your hotbar it will just overwrite the selected slot.
> Fix overwriteing held item when copying block

- README.md
- format_check.py
Fixes the following issues:
- os.walk uses os.sep in their filepaths, so on windows no folders were ignored.
- Some files like Boulder.zig use non-ascii symbols in their comments. The default open encoding on windows is your locale's ANSI codepage, and therefore caused an exception.
- The project readme incorrectly referred to the file as check_format.py. I renamed the documentation rather than the file in case somebody is using it in their workflow.
> Fix issues with check_format.py

- src/gui/windows/chat.zig
Fixes crash when reentering world in singleplayer after a chat message has faded out. Fixes error mentioned in https://github.com/PixelGuys/Cubyz/issues/649#issuecomment-2327506297, but does not affect #649
> Reset fadeOutEnd when chat lists are created.

- src/gui/windows/graphics.zig
Fix fps cap slider being shown as 144 when the settings are opened, despite being unlimited in the settings.
> Minor visual fix for fps cap in settings

- src/main.zig
This means that configurations specific to this workspace in editors don't get overwritten, which prevents accidental formatting errors whenever the game is tested.
This was affecting me when working on my PR, as I tend to run the start scripts to make sure the game compiles, and that my changes worked.
> Don't convert dotfiles to ZON, which may include editor configurations.

- src/gui/windows/creative_inventory.zig
In lieu of proper creative menu UX. 
Makes it the same width as the inventory, and cuts down on the amount of scrolling to do.
> Make creative menu 10 slots wide

- src/items.zig
I saw Quantum suggest this number a few weeks ago. 
Obviously, a larger stack size lets you carry more stuff. It also leads to less slots of the same item (ex. 4 slots of stone -> 2 slots of stone)
I tried it in survival for a little while and it felt nice. I was able to keep my torches in one slot, for example.
> Raise default stackSize to 120

- src/assets.zig
This could probably have a conflict with #1125, just in case it should be merged after if at all.
I would wait for #1125 myself, but I am worried I will eventually forget to create this PR, so I am making it now.
> Remove unused `readAllFilesInAddons` function from `assets.zig`

- assets/cubyz/biomes/desert/base.zig.zon
This is my first contribution to Cubyz. There were too many cacti spawning in the desert. I adjusted the rates so they would appear more infrequently and make the desert look more natural.
*Before*
*After*
> Reduce Cacti spawn rates

- src/assets.zig
- src/migrations.zig
This PR continues the initiative from #1125 
Additionally it fixes few small issues in previous implementation:
- migration code would show an error when loading migration file with empty object/array
- when registering migrations `commonBlocksMigrations` was used instead of `blocksMigrations` so migrations from asset folder in world would be ignored
> Add biome migrations to mitigate damage after biome renames

- src/server/storage.zig
- src/utils.zig
> Refactor `RegionFile` to use `BinaryReader` and `BinaryWriter`

- src/entity.zig
- src/network.zig
- src/utils.zig
This pull request:
- Replaces raw calls to `std.mem.readInt` with use of `BinaryReader`
- Changes treatment of corrupted/malicious payloads from crashing server to ignoring and reporting in log.
> Refactor `ClientEntityManager.serverUpdate` to use `BinaryReader`

- .github/workflows/ci.yml
- src/utils/list.zig
Cubyz once switched to its own `pageSize`, but since then the standard library was upgraded to better represent hardware and software variation. This PR allows for running on ARM Linux and MacOS.
> Fix page sizes

- src/gui/windows/delete_world_confirmation.zig
This pull request resolves double free reported by zig at a cost of one extra allocation. Double free occurs when game is closed after entering and exiting the world because exiting the world invokes `gui.deinit();gui.init()` to clear UI and frees `deleteWorldName` string that is not realocated when `gui.init()` is called.
```
C:\Users\argma\dev\Cubyz7\compiler\zig\lib\std\mem\Allocator.zig:411:40: 0x7ff7c4313367 in dupe__anon_9435 (Cubyzig.exe.obj)
const new_buf = try allocator.alloc(T, m.len);
^
C:\Users\argma\dev\Cubyz7\src\utils.zig:859:29: 0x7ff7c43bf950 in dupe__anon_31922 (Cubyzig.exe.obj)
return self.allocator.dupe(T, m) catch unreachable;
^
C:\Users\argma\dev\Cubyz7\src\gui\windows\delete_world_confirmation.zig:27:45: 0x7ff7c4497531 in setDeleteWorldName (Cubyzig.exe.obj) …
```
> Double free reported in GUI code

- src/blocks.zig
- src/chunk.zig
- src/rotation.zig
This pull request adds functions for rotating block data around Z axis.
> Add `rotateZ` for all rotations

- src/assets.zig
> Extract `createAssetStringID`

- src/rotation/branch.zig
- src/rotation/carpet.zig
- src/rotation/fence.zig
- src/rotation/log.zig
- src/rotation/planar.zig
- src/rotation/stairs.zig
- src/rotation/torch.zig
Rotations were moved to separate files, but their `rotateZ` were not marked `pub`. Because there is default implementation for that function (noop) it was not immediately visible that custom `rotateZ` are not detected.
> Fix `rotateZ` after rotation move

- src/utils.zig
This pull request adds unit tests for `BinaryReader` and `BinaryWriter` which verify that data does not change after being serialized and deserialized. Tests cover significant edge cases present in possible inputs.
Resolves: #1262
> Add tests for `BinaryReader` and `BinaryWriter`

- src/gui/windows/debug_network.zig
- src/gui/windows/debug_network_advanced.zig
- src/gui/windows/invite.zig
- src/network.zig
- src/renderer/lighting.zig
- src/server/server.zig
- src/settings.zig
- src/utils.zig
- src/utils/list.zig
as described in #1259 
- ~~Investiage crash from multiplayer session~~ I have fixed many issues since then and cannot reproduce it, so I'll assume it was silently fixed.
→ I tried using a hashmap+RangeBuffer, but the result was slower. The main bottleneck are the syscalls anyways
- ~~implement delayed acks~~ → extracted to issue #1315 
- ~~Use a monotonic clock~~ → extracted to issue #1314 
- ~~Readd the bruteforcing port section~~ → extracted to issue #1316 
→ Maximum bandwidth on localhost now reaches 140 MB/s, it's a bit fragile though, but most of the time is spent on the `sendto` syscall, so I'm fairly confident that this is the most I can get without path MTU discovery.
→ around 22-31 ms between breaking a block and receiving the block drop on localhost, most of it comes from the 10 …
> The new network system

- src/blocks.zig
- src/items.zig
- src/server/command/_command.zig
- src/server/terrain/biomes.zig
- src/server/terrain/structure_building_blocks.zig
New message samples:
```
Registered command: '/clear'
Registered command: '/gamemode'
Registered command: '/help'
Registered block:     0 'cubyz:air'
Registered block:     1 'cubyz:chalk/grey'
Registered block:     2 'cubyz:pine_log'
Registered block:     3 'cubyz:cloth/lime'
Registered block:     4 'cubyz:clay'
Registered block:     5 'cubyz:iron_ore'
Registered item:     0 'cubyz:chalk/grey'
Registered item:     1 'cubyz:pine_log'
Registered item:     2 'cubyz:cloth/lime'
Registered item:     3 'cubyz:clay'
Registered item:     4 'cubyz:iron_ore'
Registered tool: 'cubyz:pickaxe'
Registered surface biome:     0 'cubyz:tall_mountain/slope5'
Registered    cave biome:     1 'cubyz:cave/void/void_crystal'
Registered surface biome:     2 'cubyz:prairie/dry_spell'
Registered surface biome: …
```
> Unify 'Registered x' log message format

- assets/cubyz/blocks/obsidian.zig.zon
Currently ores cannot spawn on obsidian, preventing any ores from appearing in lava caves. This fixes that.
> Allow ores on obsidian

- build.zig
- test/runner.zig
Source: https://github.com/ziglang/zig/blob/0.14.0/lib/compiler/test_runner.zig
With our formatting applied, no other changes.
For some reason formatter didn't like it when I placed `runner.zig` in `src/` so I just moved it to `test/`, honestly, maybe for the best.
> Add zig test runner

- src/server/terrain/simple_structures/SbbGen.zig
- src/server/terrain/structure_building_blocks.zig
Resolves: #1250
There are two recommended ways to specify sentinel (empty) child:
- `.structure = null` - explicitly setting `structure` field to null
- `.structure = ""` - using empty ID string (it is not a valid ID)
```zig
.{
.blueprint = "<id>",
.children = .{
.blue = .{
.{.structure = null, .chance = 1.0},
.{.structure = "", .chance = 1.0},
},
},
}
```
Mind that empty child list declaration is still not valid, you must explicitly specify at least one empty child.
This is to avoid accidentally omitting children.
**invalid**:
```zig
.{
.blueprint = "<id>",
.children = .{
.blue = .{},
},
}
```
If it is intentional you can explicitly set child to `null`:
**valid**:
```zig
.{
.blueprint = "<id>",
.children = .{
.blue = null,
},
}
```
> [Structure Building Block] Allow specifying empty / sentinel children

- assets/cubyz/blocks/coal_ore.zig.zon
As discussed during playtest, coal ore should be lowered, both because irl its soft and because it is annoying to mine in game.
> Lower coal ore health

- assets/cubyz/items/iron_ingot.zig.zon
Currently Copper beats iron due to its low swing time.
This makes iron more elastic, giving it the same swing time as copper.
Both a copper-head and an iron-head pickaxe now have a swing time of 0.12s
This makes iron strictly better than copper, reducing it from the best metal in the game to a step in the progression, it's still required to mine iron. However the plan is to give it a come-back in the end game due to its high conductivity.
> Make iron more elastic

- src/block_entity.zig
- src/chunk.zig
- src/renderer/chunk_meshing.zig
> Refactor how block entity unloading works and unloading things on the client side

- src/renderer.zig
This makes the DPS statistic more accurate and reduces the impact from off-by-one errors as described in #1643
fixes #1656 
@ikabod-kee please check this out
> Speed boost when breaking a block based on leftover damage

- src/gui/components/TextInput.zig
- src/gui/windows/creative_inventory.zig
Although major UI changes are planned, they are expected in rather far future. Unfortunately current state of creative inventory makes it really frustrating to use when building and when testing newly added blocks. Therefore I have implemented a dead simple search bar which filters out all items with IDs that don't contain the searched phrase. I also made a sin of (subjectively) improving the look of item list by padding last row of item list with empty immutable slots if it was not filled with items found.
> QoL changes for creative inventory

- src/block_entity.zig
- src/chunk.zig
- src/renderer/chunk_meshing.zig
- src/renderer/lighting.zig
- src/renderer/mesh_storage.zig
- src/server/storage.zig
- src/server/terrain/chunkgen/TerrainGenerator.zig
- src/server/world.zig
- src/utils.zig
After failing in #1725 I decided to use a different approach at atomizing the palette compressed data, I added a new indirection which can be used to swap the entire content in one atomic operation. This should make the process itself cheaper than what I had implemented before.
related: https://github.com/PixelGuys/Cubyz/issues/1471 https://github.com/PixelGuys/Cubyz/issues/1413
improves https://github.com/PixelGuys/Cubyz/issues/277
Remaining work:
> Make reading light data thread safe without mutexes

- assets/cubyz/blocks/chest/baobab.zig.zon
- assets/cubyz/blocks/chest/birch.zig.zon
- assets/cubyz/blocks/chest/mahogany.zig.zon
- assets/cubyz/blocks/chest/pine.zig.zon
- assets/cubyz/blocks/chest/willow.zig.zon
- assets/cubyz/recipes/wood_recipes.zig.zon
- src/Inventory.zig
- src/block_entity.zig
- src/blueprint.zig
- src/game.zig
- src/gui/gui.zig
- src/gui/windows/creative_inventory.zig
- src/gui/windows/inventory_crafting.zig
- src/gui/windows/shared_inventory_testing.zig
- src/gui/windows/workbench.zig
- src/network.zig
- src/renderer/chunk_meshing.zig
- src/server/server.zig
- src/server/world.zig
Progress:
→ it becomes uninteractible
fixes #1060
> Add chests
